### ISSUE TITLE
Postgres Setup

### ISSUE THREAD

**Issue by ravinder-Olivier** [ISB3DPRINTERS/teachers-console#4]
@RedstoneWizard08, hey I was having some trouble getting postgresto work with the project. It compiled just fine, but when running it, it tells me 
``Error: BadConnection("connection to server at \"localhost\" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"\nconnection to server at \"localhost\" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"\n")``
I did setup a basic postgres on that port and there is the user there. But what password am i supposed to set for it, it has no password as of now.

Thanks

**Comment by RedstoneWizard08** [comment]
Run `sudo -u postgres psql`
Execute `ALTER USER postgres WITH PASSWORD '[password here]';`
Execute `\q`
The connection string should then be: `postgresql://postgres:[password here]@localhost:5432/tc-dev`
Therefore the content of `.env` in the directory where you ru n the server should be:
```sh
DATABASE_URL=postgres://postgres:[password here]@localhost:5432/tc-dev
```

**Comment by ravinder-Olivier** [comment]
Thanks, also, how come the path is tc-dev? Just curious

Sent via the Samsung Galaxy S21 Ultra 5G, an Unlocked 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RedstoneWizard08** [comment]
It's not a path, it's the name of the database.

`postgresql://[username]:[password]@[host]:[port]/[database_name]`
